const tintColorLight = '#141313';
const tintColorDark = '#fff';

export default {
  light: {
    backHeaderIcon: tintColorLight,
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    border: '#fafafa',
    priceEven: '#333',
    priceRise: '#c34042',
    priceFall: '#0966c6',
    bitcoinBox: '#f2f2f5',
    tableHeaderBackground: '#f2f2f5',
    kimchiPercentage: '#339133',
    exchangeRate: '#999',
    binanceExchangeRatePrice: '#a9a9a9',
    noticeBackground: '#141313',
    noticeText: '#fff',
    referralBox: '#fafafa',
  },
  dark: {
    backHeaderIcon: tintColorDark,
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    border: '#141313',
    priceEven: '#fff',
    priceRise: '#c34042',
    priceFall: '#0966c6',
    bitcoinBox: '#141313',
    tableHeaderBackground: '#141313',
    kimchiPercentage: '#339133',
    exchangeRate: '#445',
    binanceExchangeRatePrice: '#5e5e5e',
    noticeBackground: '#fff',
    noticeText: '#141313',
    referralBox: '#141313',
  },
};
