const tintColorLight = '#141313';
const tintColorDark = '#f2f2f2';

export default {
  light: {
    backHeader: '#fff',
    backHeaderIcon: tintColorLight,
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
    border: '#fafafa',
    priceEven: '#333',
    priceRise: '#c34042',
    priceFall: '#0966c6',
    bitcoinBox: '#f2f2f5',
    tableHeaderBackground: '#f2f2f5',
    kimchiPercentage: '#339133',
    exchangeRate: '#999',
    binanceExchangeRatePrice: '#a9a9a9',
    noticeBackground: '#141313',
    noticeText: '#fff',
    referralBox: '#f5f5f8',
    footerText: '#999',
    sortActive: '#000',
    sortInActive: '#ccc',
    tabActive: '#000',
    tabInActive: '#ccc',
    description: '#a9a9a9',
    listTabActiveColor: '#0966c6',
    listTabActiveFontColor: '#fff',
    listTabInActiveFontColor: '#000',
    listTabBorder: '#eaeaea',
    listTabBackground: '#fff',
    inActivefavoriteIcon: '#dedede',
  },
  dark: {
    backHeader: '#141313',
    backHeaderIcon: tintColorDark,
    text: '#f2f2f2',
    background: '#090909',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
    border: '#141313',
    priceEven: '#fff',
    priceRise: '#c34042',
    priceFall: '#0966c6',
    bitcoinBox: '#141313',
    tableHeaderBackground: '#141313',
    kimchiPercentage: '#339133',
    exchangeRate: '#445',
    binanceExchangeRatePrice: '#5e5e5e',
    noticeBackground: '#f5f5f8',
    noticeText: '#141313',
    referralBox: '#141313',
    footerText: '#445',
    sortActive: '#fafafa',
    sortInActive: '#454545',
    tabActive: '#fafafa',
    tabInActive: '#454545',
    description: '#555',
    listTabActiveColor: '#0966c6',
    listTabActiveFontColor: '#fff',
    listTabInActiveFontColor: '#666',
    listTabBorder: '#222',
    listTabBackground: '#222',
    inActivefavoriteIcon: '#454545',
  },
};
